###############################################################
# Program:
#     Project 10, Skeet
#     Brother Burton, CS241
# Author:
#     David Brewerton
# Summary:
#     This is my skeet shooting program. You can move it up and down, press Right to shoot and it will aim in that direction
# Above and Beyond
#     When you submit your final project (not for milestones),
#     list anything here that you did to go above and beyond
#     the base requirements for your project.
###############################################################


LFLAGS = -lglut -lGLU -lGL

###############################################################
# Build the main game
###############################################################
a.out: game.o uiInteract.o uiDraw.o point.o rifle.o velocity.o bird.o bullet.o sacredBird.o toughBird.o standardBird.o
	g++ game.o uiInteract.o uiDraw.o point.o rifle.o velocity.o bird.o bullet.o sacredBird.o toughBird.o standardBird.o $(LFLAGS)

###############################################################
# Individual files
#    uiDraw.o      Draw polygons on the screen and do all OpenGL graphics
#    uiInteract.o  Handles input events
#    point.o       The position on the screen
#    ground.o      Handles the ground / world
#    game.o        Handles the game interaction
###############################################################
uiDraw.o: uiDraw.cpp uiDraw.h
	g++ -c uiDraw.cpp

uiInteract.o: uiInteract.cpp uiInteract.h
	g++ -c uiInteract.cpp

point.o: point.cpp point.h
	g++ -c point.cpp

game.o: game.cpp uiDraw.h uiInteract.h point.h
	g++ -c game.cpp
 
 
#######################################################################
# ADD YOUR ADDITIONAL RULES HERE!
#
# Then, don't forget to add them to the dependecy list for a.out above.
#######################################################################
rifle.o: rifle.cpp rifle.h point.h uiDraw.h
	g++ -c rifle.cpp
 
velocity.o: velocity.cpp velocity.h
	g++ -c velocity.cpp

bird.o: bird.cpp bird.h velocity.h point.h
	g++ -c bird.cpp

bullet.o: bullet.cpp bullet.h velocity.h point.h
	g++ -c bullet.cpp
 
sacredBird.o: sacredBird.cpp sacredBird.h bird.h velocity.h point.h
	g++ -c sacredBird.cpp

toughBird.o: toughBird.cpp toughBird.h bird.h velocity.h point.h
	g++ -c toughBird.cpp
 
standardBird.o: standardBird.cpp standardBird.h bird.h velocity.h point.h
	g++ -c standardBird.cpp
###############################################################
# General rules
###############################################################
clean:
	rm a.out *.o
